<?php


class DashboardController extends ControllerBase
{
    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){

    }


}