<?php



class ErrorController extends ControllerBase
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function show404Action()
    {

    }

    public function show500Action()
    {

    }


}