<?php

class IndexController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function indexAction()
    {
        if($this->session->get('auth'))
        {
            $this->dispatcher->forward([
                "controller"    => "dashboard",
                "action"    =>  "index"
            ]);
        }


    }

}

