<?php


class PartnersController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

    }


    public function createcustomersAction()
    {
        $form = new NewcustomerForm();

        $this->view->form = $form;
    }


}