<?php


class SessionController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function _registerSession(Users $user)
    {
        $this->session->set('auth', array(
            'id'    =>  $user->id,
            'username'  =>  $user->username
        ));
    }




    public function startAction()
    {
        if($this->request->isPost())
        {
            $username = $this->request->getPost('username');
            $password = $this->request->getPost('password');

            $user = Users::findFirst(array(
                "username = :username: AND password = :password:",
                'bind' => array('username'=>$username, 'password'=> sha1($password))
            ));

            if($user != false){
               $this->_registerSession($user);
                $this->flash->success ('Welcome, '.$user->username);

                return $this->dispatcher->forward(
                    [
                        "controller"    =>  "dashboard",
                        "action"    =>  "index"
                    ]
                );
            }

            $this->flash->error("wrong email & password combination");
        }

        return $this->dispatcher->forward(
            [
                "controller" => "index",
                "action"    => "index"
            ]
        );
    }


    public function endAction()
    {
        $this->session->remove('auth');
        $this->flash->success('Logged out.');

        return $this->dispatcher->forward([
            "controller"    =>  "index",
            "action"    =>  "index"
        ]);
    }
}